version: "3.5"

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/switt/data/wordpress


  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/switt/data/mariadb


services:
  mariadb:
    container_name: mariadb
    build: ./mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
    expose:                         
      - "3306"
  
  wordpress:
    container_name: wordpress
    build: ./wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: unless-stopped
    expose: 
      - "9000"

  nginx:
    container_name: nginx
    build: ./nginx
    env_file:
      - .env
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: unless-stopped
